server:
  port: 8020
spring:
  application:
    #    应用名称 （nacos会将该名称当做服务名称）
    name: order-ribbon-server
  cloud:
    nacos:
      server-addr: 114.115.161.43:8847
      #      server-addr: 127.0.0.1:8848
      discovery:
        username: nacos
        password: nacos
        #        命名空间 可以设置为public prod生产环境 dev开发环境
        namespace: public

#        永久实例 宕机也不会删除实例  默认true:临时实例 当服务宕机 超过心跳 就会将实例释放删除
#        ephemeral: false
#        权重 负载均衡策略 权重越高分配的流量就越大
#        weight: 1
#        分组  默认DEFAULT_GROUP
#        group: DEFAULT_GROUP
#        默认取 ${spring.application.name} 也可通过此处进行配置
#        service: stock-server
#         元数据 可以结合元数据做扩展
#        metadata: version=1