server:
  port: 8050
spring:
  application:
    #    应用名称 （nacos会将该名称当做服务名称）
    name: order-openfeign-server
  cloud:
    nacos:
      server-addr: 114.115.161.43:8847
      #      server-addr: 127.0.0.1:8848
      discovery:
        username: nacos
        password: nacos
        #        命名空间 可以设置为public prod生产环境 dev开发环境
        namespace: public

#springboot默认日志级别是info feign的debug日志级别不会输出
logging:
  level:
    net.mddn.order.openfeign.feign: debug   # 只配置feign目录下的日志级别 无包地址则是全局

#feign 日志局部配置
feign:
  client:
    config:
      product-nacos-server:  #配置服务名
        loggerLevel: BASIC
        contract: feign.Contract.Default  #设置默认的契约-还原成原生注解
        #连接超时时间 默认2秒
        connectTimeout: 3000
        #请求处理超时时间 默认5秒
        readTimeout: 10000
        requestInterceptors[0]:
          net.mddn.order.openfeign.intercptor.feign.CustomFeignIntercepror
